name: scanera
description: Final semester project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.2
  dropdown_button2: ^1.8.9
  equatable: ^2.0.3
  figma_squircle: ^0.5.3
  flutter_blue_plus: ^1.3.1
  get_it: ^7.2.0
  go_router: ^5.1.9
  flutter_keyboard_visibility: ^5.4.0
  injectable: ^1.5.4
  intl: ^0.17.0
  json_view: ^0.4.0
  logging: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.4
  sensors_plus: ^2.0.1
  shared_preferences: ^2.0.15
  wifi_hunter: ^1.1.0+1


dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/helvetica_neue.otf
          weight: 400
        - asset: assets/fonts/helvetica_neue_bold.otf
          weight: 700
    - family: Iceland
      fonts:
        - asset: assets/fonts/Iceland-Regular.ttf
          weight: 400
